In [ ]:
import numpy as np


In [ ]:
 arr = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)   
 arr 

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.ndim)

2


In [ ]:
print(arr.shape)

(3, 3)


In [ ]:
print(arr.size)

9


In [ ]:
print(arr.dtype)

float64


In [ ]:
lst=[1,2,3,4,65]
arr2=np.array([lst])
print(arr2)


[[ 1  2  3  4 65]]


In [ ]:
zero=np.zeros((3,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
full=np.full((3,3),7,dtype=complex)
full

array([[7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j, 7.+0.j]])

In [ ]:
random=np.random.random((3,3))
random

array([[0.14792573, 0.15675126, 0.20163511],
       [0.21102086, 0.51724274, 0.07980167],
       [0.60992326, 0.76629415, 0.33932137]])

In [ ]:
t=np.arange(1,10,2)
t

array([1, 3, 5, 7, 9])

In [ ]:
l=np.linspace(1,10,99999)
l

array([ 1.     ,  1.00009,  1.00018, ...,  9.99982,  9.99991, 10.     ])

In [ ]:
r=arr.reshape((1,3,3))
r

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

In [ ]:
f=arr.flatten()
f

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [ ]:
temp= arr[:2,::2]
temp

array([[-1.,  0.],
       [ 4.,  6.]])

In [ ]:
cond = arr > 2
temp = arr[cond]
temp

array([4. , 4. , 6. , 2.6, 7. , 8. , 3. , 4. ])

In [ ]:
Trans_arr = arr.T
print("\nTranspose of Array: ")
print(Trans_arr)


Transpose of Array: 
[[-1.   4.   2.6  3. ]
 [ 2.  -0.5  0.  -7. ]
 [ 0.   6.   7.   4. ]
 [ 4.   0.   8.   2. ]]


In [ ]:
AM=arr.max(axis=0)
AM

array([4., 2., 7., 8.])

In [ ]:
AM=arr.cumsum(axis=0)
AM

array([[-1. ,  2. ,  0. ,  4. ],
       [ 3. ,  1.5,  6. ,  4. ],
       [ 5.6,  1.5, 13. , 12. ],
       [ 8.6, -5.5, 17. , 14. ]])

In [ ]:
num_list = [6,7,10,12,13,4,8,12]
num_sum = sum(num_list)
mean = num_sum / len(num_list)
print(num_list)
print("Mean of the above list of numbers is: " + str(round(mean,2)))

[6, 7, 10, 12, 13, 4, 8, 12]
Mean of the above list of numbers is: 9.0


In [ ]:
list1=[6,7,10,12,13,4,8,12]
mean = sum(list1)/len(list1)
len = int(len(list1))
for i in list1:
  variance=(i+mean)/len
print(variance)

2.625
